### PR TITLE
feat(unprivileged): run unprivileged nginx to support arbitrarily assigned user ID

### PR DESCRIPTION
**Pull request by marius-boden-sva**
Use unprivileged nginx to support arbitrarily assigned user ID to be able to run the image e.g. on Red Hat Openshift

### Description

The dockerfile uses the nginxinc/nginx-unprivileged image instead of the standard nginx image.

This enables the container to run as a non-root user which is an improvement to the container security and enables running the container on distributions such as OpenShift by default.

### Motivation and Context

The change is necessary as the previous version required nginx to run as root to be able to read/write so several default paths.

Fixes https://github.com/swagger-api/swagger-editor/issues/2931

### How Has This Been Tested?

Because of a missing access token to the apidom npm packages this can not be tested locally anymore!!!

originally this could be tested the following way:
Dependencies: npm ci
Build: npm build
Docker Build: docker build -t swagger-editor-unprivileged .
Docker Run: docker run -p 8080:8080 -u 100000 swagger-editor-unprivileged
Visit in browser: http://localhost:8080/

### My PR contains... 

- [X] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [X] Improvements (misc. changes to existing features)
- [X] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [X] are not breaking changes.

### Documentation
- [X] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [X] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by marius-boden-sva** [comment]
@char0n as you guys dropped the nginx config I did so as well. Because of a missing auth token for the apidom npm packages I could not build an test locally. Please test before merge ;)

**Comment by char0n** [comment]
@marius-boden-sva thanks. 

Regarding installing ApiDOM: https://github.com/swagger-api/apidom#installation
Specifically authenticating to GitHub packages: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#authenticating-to-github-packages

**Comment by char0n** [comment]
Superseded by https://github.com/swagger-api/swagger-editor/pull/3705

**Comment by char0n** [comment]
Next time `5.0.0-alpha.*` is released, the `swaggerapi/swagger-editor:next-v5-unprivileged` tag will be available in DockerHUB.

**Pull request closed without merging**
