### PR TITLE
Add Docker steps to README

### PR DESCRIPTION
**Pull request by agonzalezro**

### CODE REVIEW

**Comment by mohsen1** [comment]
We have Docker help in development guide: https://github.com/swagger-api/swagger-editor/blob/master/docs/development.md#running-with-docker

It would be nice if you can improve on that. Please don't remove code blocks with language name. They help syntax highlighter highlight the code better.

Thanks!

**Comment by agonzalezro** [comment]
Hi @mohsen1 & thanks for your comments.

I am sorry for removing the language specification from the block, I just thought that in this particular examples the highlighter would do almost the same job and in case that you were reading plain text it would be easier to follow.

About the docker run, you are right, I didn't realise about that file but to be honest, I wouldn't specify this way of running it just for developers, it's pretty useful outside dev-mode. Perhaps the best option would be create an automated build on the docker hub and just run that one instead showing how to build it on this `README`?

**Comment by mohsen1** [comment]
We decided not to maintain an official image in Docker Hub for Swagger Editor. Please feel free to create and maintain one. There are a bunch of them in Docker Hub but they're not up to date.

**Comment by agonzalezro** [comment]
Ok @mohsen1. Should I close this PR?

**Pull request closed without merging**
