### PR TITLE
multi stage docker build & run as nginx user

### PR DESCRIPTION
**Pull request by epsilonhalbe**
updated Dockerfile & Readme to handle the dockerized build without the necessity of installing node/npm and iltorb via multi-stage build and changed the running user inside the docker container to be nginx.

Note: the alpine build container uses node 8.11.x which produces a bunch of security warnings/vulnerabilities mostly for libraries this project depends on. I guess they are worth looking at.

### CODE REVIEW

**Comment by epsilonhalbe** [comment]
is there anything you need for my PR?

The failing jenkins test, cannot be caused by my commit - as I did not modify a single line of code only the docker build file + the documentation.

I try to rebase every week so my changes don't get outdated.

BR Martin

**Comment by shockey** [comment]
@epsilonhalbe, no worries on the CI fail, that happens every now and again, there’s a finicky async test that gives us trouble. 

I’ll do my best to review this PR this week - rest assured we have eyes on it!

**Comment by shockey** [comment]
please build

**Comment by shockey** [comment]
closing as this has grown quite out-of-date against our current Dockerfile — feel free to reopen against master if you'd still like to see this!

**Pull request closed without merging**
