### PR TITLE
Enable "XMLHttpRequest.withCredentials" option

### PR DESCRIPTION
**Pull request by dalbani**
Makes cross-site Access-Control requests send cookies as well.

### CODE REVIEW

**Comment by jaanushansen** [comment]
I would like it very much, if the pull request would be accepted (http://stackoverflow.com/questions/36924317/how-to-use-cookies-in-swagger-editor). If you you can't add withCredentials option by default, maybe it could be made configurable?

**Comment by dalbani** [comment]
I indeed forgot to ask @saharj why she closed this bug. Should I have explained the use case?

**Comment by saharj** [comment]
The problem is that this code will break cross origin calls. We might be able to add it if the call is not cross origin.

**Comment by jaanushansen** [comment]
@saharj how is breaking cross-origin calls? I added  xhrFields: { withCredentials: true } option to the ajax call and it solved my issue and gained cookies support in swagger-editor http://stackoverflow.com/questions/36924317/how-to-use-cookies-in-swagger-editor

**Comment by saharj** [comment]
My bad, `withCredentials` is useful *only* for CORS calls. If this pull request limits adding `withCredentials` only when `isCrossOrigin()` is  true, then I will merge this pull request (or a new one that does it).

**Comment by dalbani** [comment]
Why should the `isCrossOrigin() == true` case be handled apart?
I read on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials) that:
> Setting `withCredentials` has no effect on same-site requests.

**Comment by jaanushansen** [comment]
@saharj could you please explain it even more - do you agree to merge after @dalbani's last comment or are you still waiting for a pull request with isCrossOrigin() check?

**Pull request closed without merging**
