### PR TITLE
Add print styling directives

### PR DESCRIPTION
**Pull request by cproof**
This commit fixes issue #1383 by adding some directives for printing to the editor styling.

### CODE REVIEW

**Comment by shockey** [comment]
At first glance, I don't feel great about using `. Pane1` and `. Pane2` for CSS targeting.

I know we're doing it elsewhere and it's not likely to change, but it would be best to add IDs for the Editor and UI panes so they can be targeted more specifically.

I'll circle back on this PR soon 😄

**Comment by cproof** [comment]
Any news about this pull request? 
I'd assign the ids "editor-pane" and "swagger-ui-pane" to .Pane1 and .Pane2 if this would solve the problem of missing ids for css targeting.

**Comment by shockey** [comment]
@cproof, that would be great! If that change is made, I'd be happy to merge this.

**Comment by shockey** [comment]
@cproof, yeah, I see what you're saying now, we're just pulling in the UI layout, so it'd be hard to inject ids.

In light of that, this should be fine (since it works!). Thanks for the contribution!

**Pull request merged**
