### PR TITLE
Add editorOptions from state ( relies on configsPlugin )

### PR DESCRIPTION
**Pull request by ponelat**
## TODO: First get configsSelector merged into swagger-ui.
Besides that...
This allows Ace Editor options to be controlled via state (ie: actions + selectors)

### CODE REVIEW

**Comment by shockey** [comment]
@ponelat, is there a `configsSelector` UI PR open?

**Comment by ponelat** [comment]
@shockey no `configsSelector` PR yet... stay tuned

**Comment by ponelat** [comment]
configs plugin PR in swagger-ui: https://github.com/swagger-api/swagger-ui/pull/3813

**Comment by ponelat** [comment]
Merge when happy @shockey ( since I imagine you may not want to merge on a Friday, just before a release ).

**Comment by ponelat** [comment]
ping @shockey

**Pull request merged**
