### PR TITLE
Updating petshop examples to https

### PR DESCRIPTION
**Pull request by digininja**
### Description
The petshop examples all point to http resources but there is no reason for them not to point to https.

### Motivation and Context

Lets bring it up to the modern day and HTTPS Everywhere.

### How Has This Been Tested?

All the links that I've updated work fine on HTTPS.

### My PR contains... 

- [x] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [x] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [x] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [x] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by a-abella** [comment]
please build

**Comment by digininja** [comment]
I'm not a Jenkins user so don't understand why it is failing to build and there are no usable errors given.

**Comment by a-abella** [comment]
> I'm not a Jenkins user so don't understand why it is failing to build and there are no usable errors given.

"please build" is the keyword to kick off the build automation. I saw this build was stalled so I invoked the keyword to build it again. Sorry, was not directed at you

**Comment by digininja** [comment]
I thought it might be, was just wondering why the build was failing at Jenkins

**Comment by tim-lai** [comment]
@digininja Thanks for the PR. However, it is breaking existing tests. That said, we redirect `http://petstore.swagger.io` to https, so the sample definitions are still valid.

**Comment by digininja** [comment]
They are valid, it is just better to show HTTPS rather than HTTP as best
practice.

**Pull request closed without merging**
