### PR TITLE
Fixed style for react-split-pane component.

### PR DESCRIPTION
**Pull request by fr-sutiwo**
### Description

Swagger-editor uses react-split-pane package module. But there is not included css.
Therefore we can't drag left/right freely.
That's why, I added some styles in order to do that with reference to https://github.com/tomkp/react-split-pane/blob/master/website/src/index.css

## Why is this change required? What problem does it solve?
Because we can't drag left/right freely.

## If it fixes an open issue, please link to the issue here.
Nothing.

### Screenshots (if appropriate):
drag3

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [x] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by fr-sutiwo** [comment]
@shockey please review.

**Comment by shockey** [comment]
please build

**Comment by shockey** [comment]
please build

**Comment by shockey** [comment]
thanks @fr-sutiwo!

**Pull request merged**
