### PR TITLE
update yaml-js version

### PR DESCRIPTION
**Pull request by kyeotic**
### Description
Update yaml-js to version 0.2.3

### Motivation and Context
This fixes warnings produced by webpack when bundling the editor as part of another app.

```
./node_modules/yaml-js/lib/yaml.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/yaml-js/lib/yaml.js
require.extensions is not supported by webpack. Use a loader instead.

./node_modules/yaml-js/lib/yaml.js
require.extensions is not supported by webpack. Use a loader instead.

./node_modules/yaml-js/lib/yaml.js
require.extensions is not supported by webpack. Use a loader instead.
```

### How Has This Been Tested?
I have tested this by bundling the result into our internal app and running the editor. It has no behavioral changes other than removing the warnings from webpack.

### My PR contains... 
- [x] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [x] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [x] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by kyeotic** [comment]
Anything I can do to improve this @shockey?

**Comment by kyeotic** [comment]
@shockey I have made the requested changes and the tests are now passing

**Comment by shockey** [comment]
merged. thanks @kyeotic!

**Comment by kyeotic** [comment]
hey @shockey, i can't tell if you guys have a release schedule or not, do you know when this might get published?

**Pull request merged**
