### PR TITLE
build: migrate to webpack@5

### PR DESCRIPTION
**Pull request by char0n**
Refs #2944
Succeeded #2949
Succeeded #2976

### Description

I made minimal changes that were required to migrate to webpack@5. Some changes were taken from #2949 and #2976. 

**Additional notes:**
- worker-loader still works with webpack@5 and is the only way how to inline the web worker or set other advanced web worker settings
- validation.worker - we always want web worker to be inlined for simplicity and backward compatibility
- we don't use fallback anymore in all cases, as we don't care about very old browsers that don't support web workers anymore (IE 11)
- fought through https://github.com/reduxjs/redux/issues/4174 which was resolved by regenerating package-lock file
                 

Overcomed: https://github.com/reduxjs/redux/issues/4174

### How Has This Been Tested?

Manually. **Still needs to test if primary build bundle works with webpack@4 and webpack@5**.

### My PR contains... 

- [x] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [x] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [x] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [x] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by tim-lai — APPROVED** [review]

**Comment by tim-lai** [comment]
@char0n approving PR. just need to fix merge conflict(s). Also a note to confirm Docker build after merge. Also a sidenote, fyi, and was not intending to fix in this PR, is how to handle including worker sourcemap with different oupts, related to this ticket: #2146

**Comment by char0n** [comment]
I'll address your feedback on Monday next week and ideally on Tuesday we'll go for a merge.

**Comment by char0n** [comment]
Rebased on top of current master.

**Comment by char0n** [comment]
@tim-lai transformed your feedback to additional todo list in https://github.com/swagger-api/oss-planning/issues/550

**Pull request merged**
