### PR TITLE
feat(oas3.1): integrate swagger-ui containing OpenAPI3.1 support

### PR DESCRIPTION
**Pull request by tim-lai**
### Description

- update `EditorPreviewWrapper` to render SwaggerUI if definition is OpenAPI3.1. Previously would render a fallback component
- update `swagger-ui-react` dependency

### Motivation and Context

`swagger-ui@4.16.0-alpha.3` and `swagger-ui-react@4.16.0-alpha.3` now supports OpenAPI 3.1 via `apidom`

### How Has This Been Tested?

local

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [x] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tim-lai** [comment]
@char0n Any thoughts why CI is getting an out of memory error during the build step? Could it be the `overrides` in `package.json`? Although, it builds fine on my local.

**Comment by tim-lai** [comment]
Just saw the note for swagger-client@beta, which this PR still uses swagger-client@alpha. Not sure if relevant yet.

**Comment by char0n** [comment]
I know where the issue is. It's documented in https://github.com/swagger-api/swagger-editor/issues/3856 and I'll process it during tomorrow. After it's done, I'll create PR which will supersede this PR.

**Comment by char0n** [comment]
Superseded by https://github.com/swagger-api/swagger-editor/pull/3872

**Pull request closed without merging**
