### PR TITLE
Small tweaks, export plugins and adjust react version to match swagger-ui

### PR DESCRIPTION
**Pull request by ponelat**
**export plugins and remove dead file**

**Only apply styles in editor.less to #swagger-editor and under**

**Update react versions to match swagger-ui**

### CODE REVIEW

**Comment by webron** [comment]
So the small tweaks that include changes to 39 files... what's up?

**Comment by ponelat** [comment]
This needs to be broken up into smaller PRs. Its on the TODO list. 

I think items include.
- editor-autocomplete plugins
- readOnly watermark
- editor markers
- minor style wrapping

**Comment by webron** [comment]
Can we close this PR while the smaller ones are being prepared?

**Comment by webron** [comment]
Thanks @ponelat.

**Pull request closed without merging**
