### PR TITLE
Feature: Preview Only

### PR DESCRIPTION
**Pull request by nazarhussain**
We notice that swagger-ui and swagger-editor always have gaps in features. We can cover up it by having preview only feature that will serve as swagger-ui.

### CODE REVIEW

**Comment by mohsen1** [comment]
Problem with preview only mode is it's maintenance. We have to maintain this is working for each change. Swagger Editor wants to be the editor, not the UI. It's going to have a lot more editing components in the "preview" pane so it's going to be harder to maintain this mode. 
We used to have preview only mode but decided to make editor focus on editing Swagger and UI for rendering Swagger. If Swagger UI is missing features, please make a ticket there and ask for it. 

I'm afraid I should say no to merging this although many people are asking for it. This pull request can be a good example of how you do it on your own.

**Comment by nazarhussain** [comment]
@mohsen1 I don't see any issue in maintenance. As you reviewed the changes, I just made the panels hides, I didn't made any change in the behavior of the editor. It is same behavior as opening standard editor and just click on divider to hide editor pane. 

You already have feature to click on divider to hide editor pane, I just got this behavior by configuration. What do you think?

**Comment by mudassarn** [comment]
@nazarhussain thanks a lot for bringing in this feature. It is definitely needed as swagger-ui is not that good looking. Although UI of swagger-editor rocks. When can this PR be merged? Can't wait to have this feature. Please leave me a comment when this got merged.

Thanks in advance.

**Comment by webron** [comment]
I'm afraid as @mohsen1 explained that it's unlikely we'll merge the PR. But also, as @mohsen1 mentioned, this could be a good reference to anyone looking to doing that on their own.

**Pull request closed without merging**
