### PR TITLE
JSON References resolve base path

### PR DESCRIPTION
**Pull request by saharj**
Fixes https://github.com/swagger-api/swagger-editor/issues/977

See [this comment](https://github.com/swagger-api/swagger-editor/issues/977#issuecomment-232254578)

**UI changes screenshots**
screen shot 2016-07-12 at 10 40 47 pm

**Browsers I manually tested this feature in**
* [x] Google Chrome
* [ ] Firefox
* [ ] Microsoft Edge

### CODE REVIEW

**Comment by CsatariGergely** [comment]
Hi, for some reason I do not have the whole Swagger Editor Preferences screen. I have swagger-editor-dist@3.1.9 . @saharj can you please help me to find it? :)

**Comment by webron** [comment]
@CsatariGergely There's no preferences screen in 3.X.

**Comment by CsatariGergely** [comment]
Thanks @webron for the answer, so it is not my fault that I can not find it. Where can I set the "Pointer Resolution Base Path" then?

**Comment by webron** [comment]
There's no way of doing that at the moment.

**Comment by CsatariGergely** [comment]
Sad to hear. I work with quite big swagger files and I would really need to make $ref-s work to be able to validate my work without first merging the files with a separate tool.

**Comment by webron** [comment]
File a new ticket, you never know what might happen ;)

**Pull request merged**
