### PR TITLE
WIP: Fix flawed logic in cwrp, and move around removeMarkers

### PR DESCRIPTION
**Pull request by ponelat**
Fix flawed logic in testing when to update the yaml in the editor.
As well as move around removeMarkers() ( to ensure no ghosting )

TODO: Tests!

@shockey any thoughts on your side for markers? Everytime I touch them, I feel the need for a shower.

### CODE REVIEW

**Comment by ponelat** [comment]
Tests incoming!

**Comment by shockey** [comment]
@ponelat any updates here? is this still being worked on?

**Comment by ponelat** [comment]
@shockey Yes, slowly surely. Got pulled away, but hopefully can get a chance to push this up. The tests include changes ( relatively minor ) to the editor logic. 
I'll put them in its own PR, will need to think about what to do with this one... :thinking:

**Comment by shockey** [comment]
@ponelat, any updates here?

**Comment by ponelat** [comment]
Ping back :) Going to close this out this week :crossed_fingers:

**Pull request closed without merging**
