### PR TITLE
Fix typo in *.js files

### PR DESCRIPTION
**Pull request by pscheich**
I fixed 5 typos in .js.map and a .js file. seperated -> separated

### Description
I fixed 5 typos in .js.map and a .js file. seperated -> separated

```
$ grep -rwl seperated
dist/swagger-editor-bundle.js.map
dist/swagger-editor-es-bundle-core.js.map
dist/swagger-editor-es-bundle.js.map
dist/swagger-editor.js.map
src/plugins/editor-autosuggest-oas3-keywords/oas3-objects.js
```

### Motivation and Context
Five typos less.

### How Has This Been Tested?
It's not tested. They are just typos in comments and strings.

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [x] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by char0n** [comment]
@pscheich can you please limit your changes to [src/plugins/editor-autosuggest-oas3-keywords/oas3-objects.js](https://github.com/swagger-api/swagger-editor/pull/2932/files#diff-9772f9a03e324ffe55edfb3f0013ba754454a51d6d512494c99ff0dc0f016ff2)? Distribution build fragments you modified as well are considered immutable.

Thanks

**Review by char0n — CHANGES_REQUESTED** [review]
Thanks for contributing! Please have a look at my comment about limiting the changes.

**Comment by pscheich** [comment]
Hey @char0n, thanks for your feedback, I removed the changes in dist.

**Review by char0n — APPROVED** [review]
Thanks for contributing!

**Pull request merged**
