### PR TITLE
Deprecate android codegen

### PR DESCRIPTION
**Pull request by cbornet**
See #713 and https://github.com/swagger-api/swagger-codegen/issues/1353

### CODE REVIEW

**Comment by cbornet** [comment]
Is it really an issue with the PR or is the CI broken ?

**Comment by cbornet** [comment]
See #715

**Comment by fehguy** [comment]
I don't really think we want to only support a single java client.  Keeping Android separate is a good idea, and even though the manifest has been added to java, I think it should go back to being separate.

**Comment by cbornet** [comment]
Well, the current android generator is outdated and I think people should not be given the false idea that they should use it instead of one of the more advanced java libs which also support android. For an android app, I would for instance recommend java-retrofit, not the deprecated apache client.

**Comment by fehguy** [comment]
Agreed but I would rather address that root problem in the codegen

**Pull request closed without merging**
