### PR TITLE
[security] retain the authentication

### LINKED ISSUE #311: Problems in stored authentication
When change a security the stored authentication remains unchanged

### PR DESCRIPTION
**Pull request by iflamed**
fix #311 

> fix it by create a hash key to map the security property with security options

### CODE REVIEW

**Comment by mohsen1** [comment]
This is good. If you could, please add some test.

**Comment by mohsen1** [comment]
Also please rebase your `fix` commits

**Comment by iflamed** [comment]
ok, I will learn how to add some test for this commit.

**Comment by iflamed** [comment]
I have added the e2e test for the stored authentication.

**Comment by mohsen1** [comment]
Very nice! :+1:

**Pull request merged**
