### PR TITLE
Fixed sub-schema selection for additionalProperties

### LINKED ISSUE #1662: "Type" keyword has not been correctly parsed by editor if used as a property attribute in a definition in the field "additionalProperties"
_From @matterove on February 5, 2018 13:15_

This should be a problem only in the editor validation because the client is correctly generated

In attachement you can find an example of the issue
[TypeBugExample1.txt](https://github.com/swagger-api/swagger.io/files/1695202/TypeBugExample1.txt)

_Copied from original issue: swagger-api/swagger.io#210_

### PR DESCRIPTION
**Pull request by jemerald**
### Description
The current spec sub-schema selector returns the children nodes of `additionalProperties` instead of the `additionalProperties` node itself. This is incorrect and causes potential validation bugs

Added new unit tests for the `allSchemas` selector

### Motivation and Context

Fixes #1662

### How Has This Been Tested?
Added a whole bunch of unit tests for selectors

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [x] My changes can and should be tested by unit and/or integration tests.
- [x] If yes to above: I have added tests to cover my changes.
- [x] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jemerald** [comment]
@shockey not sure why the one test breaks... should have nothing to do with my changes?

**Comment by jemerald** [comment]
Hmm... force pushed a commit subject change to trigger the build, and the test passed (even though swagger-client still throws the same exception).

Had a look at some historically builds, the same exception was there since PR1656... Any idea?

**Comment by shockey** [comment]
@jemerald, can you link me to a Travis build that failed? I don't see it in the build history :/

There is a test that intermittently fails for me locally, it's part of the semantic validation. That system is async, and we use a hard cutoff (60ms iirc) to allow the async stuff to settle, and every once in a while it doesn't make it.

**Comment by jemerald** [comment]
@shockey here it is, you can find it by clicking on the "Pull Requests" tab
https://travis-ci.org/swagger-api/swagger-editor/builds/338293608

**Comment by shockey** [comment]
Hmm, that is strange.

I couldn't get it to happen, so I'm just going to call it a fluke unless it shows up again 😄

**Comment by shockey** [comment]
thanks @jemerald!

**Pull request merged**
