### PR TITLE
feature: Topbar `Edit > Convert to OpenAPI 3` menu item

### PR DESCRIPTION
**Pull request by shockey**
This PR:

* adds a new item to the Topbar's Edit menu
* adds a new `swagger2ConverterUrl` configuration option
* adds a new state plugin namespace, `topbar`, which is used for modal show/hide state management

---

This PR breaks some conventions:

#### Bare service URL instead of URL leading to a service's OpenAPI document

For the Generator menu items, we allow users to supply a URL pointing to an OpenAPI document for a Swagger Codegen service. Here, we just ask for a bare conversion URL to make POSTs to. 

This is intentional - conversion, unlike code generation, only requires a single endpoint, so doing the legwork for processing an OpenAPI document doesn't make sense here.

#### Code structure for the menu item

This menu item is housed within its own plugin which extends the Topbar component. This is in contrast to most other menu items, which are implemented directly in the Topbar component (exception being the Insert menu).

This is intentional as well - in fact, the Topbar component is quite overloaded at this point, so we would do well to factor out each existing menu item into a plugin.

### CODE REVIEW

**Comment by shockey** [comment]
please build

**Comment by shockey** [comment]
please build

**Comment by shockey** [comment]
please build

**Comment by shockey** [comment]
please build

**Comment by shockey** [comment]
please build

**Comment by neo7337** [comment]
What if I want to remove this menu item **Convert to OpenAPI 3** from the editor that I have integrated with my application. Is there a way to do that? @shockey

**Pull request merged**
