### PR TITLE
change generator URL to use https so they are not blocked

### PR DESCRIPTION
**Pull request by gitolicious**
When calling a deployed Swagger Editor in i.e. Chrome via a https url, the generators are blocked because the link is http and the browser does not allow https/http mixed-content. By loading the generators via https, this problem is solved.

### CODE REVIEW

**Comment by shockey** [comment]
Good catch @gitolicious!

Can you merge/rebase your branch so I can merge this PR?

**Comment by gitolicious** [comment]
Done. (Hope I got it right...)

**Comment by shockey** [comment]
Looks like something got out of whack - no worries, I'll merge the change in in another PR and attribute the commit to you.

**Comment by gitolicious** [comment]
Thanks a lot!

**Pull request closed without merging**
