### PR TITLE
Prefill request parameters with example data

### PR DESCRIPTION
**Pull request by wolli2710**

### CODE REVIEW

**Comment by mohsen1** [comment]
If example is conforming to the schema you don't really need to traverse the example and add it layer by layer. There are some style errors (single quotes and other styling issues). Please add an end-to-end test for this.

**Comment by wolli2710** [comment]
@mohsen1 Thanks for the feedback, I updated my changes but I don't get how it's possible to prefill the form without traversing the examples. Do you have any hints on that one?

**Comment by mohsen1** [comment]
You basically need to attach the example to parameters in bodyModel. The form generator will figure it out. 

One thing we need to make sure is when example is not conforming to the schema. Since that is possible we need to check it before assignment

**Comment by wolli2710** [comment]
I can't find a way to attach the example to the parameters in bodyModel without traversing. When I use the provided example data this would be possible, because it's a flat structure. When there is nested data like in the json-api standard eg. data, attributes, relationships, included... it is only possible with traversing right?

When you say we need to check, if the example is conforming to the schema you mean the type? This could be a bit tricky, because when you want to check a type in js and describe an api of a service, written in a strong typed language this is not possible?

**Pull request closed without merging**
