### PR TITLE
deploy to npm using TravisCI

### LINKED ISSUE #860: Publish to npm via TravisCI
Publish to npm via TravisCI. See [here](https://docs.travis-ci.com/user/deployment/npm/)

### PR DESCRIPTION
**Pull request by saharj**
Fixes #860 

@fehguy please review

### CODE REVIEW

**Comment by fehguy** [comment]
@saharj are you looking to publish builds from master or just releases?

**Comment by saharj** [comment]
@fehguy I'm looking to release  2.10.0

**Comment by saharj** [comment]
@fehguy With this PR, TrivisCI will deploy whenever we push a new tag.

**Comment by fehguy** [comment]
Sure looks good to me!

**Pull request merged**
